version: "3"
services:
  web:
    build: .
    ports:
      - "8081:80"
    networks:
      - webnet

  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - "./redis/data:/data"
    command: redis-server --appendonly yes
    networks:
      - webnet


networks:
  webnet:


